traversability_analysis:
  ros__parameters:
    pointCloudTopic: "lio_sam/mapping/map_global"
    pose_topic: "/pose"
    costMapTopic: "map"

    map_frame_id: "map"
    circle_radius: 10.0
    cell_resolution: 0.2
    T_diff: 0.7
    T_high: 0.2
    T_low: -0.2
    max_height: 2.0