traversability_analysis:
  ros__parameters:
    pointCloudTopic: "lio_sam/mapping/map_global"
    pose_topic: "/pose"
    costMapTopic: "map"

    map_frame_id: "map"
    circle_radius: 10.0
    cell_resolution: 0.2
    T_diff: 0.7
    T_high: 0.2
    T_low: -0.2
    max_height: 2.0
    Treshold: 9.0
    mean_grass: 24.8704
    variance_grass: 20.9897
    T_prob: 1.0e-7
    num_grids_min: 9

    T_ratio: 1.7
    T_l: 1.7
    T_s: 1.7

    T_neg: -0.2
    T_pos: 0.2
    T_seg: 0.1
    T_inliners: 0.6
    T_Iterations: 1.2
    Max_traversable_angle: 65.0