traversability_analysis:
  ros__parameters:
    pointCloudTopic: "lio_sam/mapping/map_global"
    pose_topic: "odometry/imu"
    costMapTopic: "local_map"

    map_frame_id: "map"
    circle_radius: 10.0
    cell_resolution: 0.17
    T_diff: 0.4
    T_high: 0.2
    T_low: -0.2
    max_height: 2.0
    Treshold: 9.0
    mean_grass: 24.8704
    variance_grass: 20.9897
    T_prob: 1.0e-7
    num_grids_min: 9

    T_ratio: 20.0
    T_l: 0.2
    T_s: 4.0

    T_neg: -0.15
    T_pos: 0.15
    T_seg: 0.4
    T_inliners: 0.85
    T_Iterations: 1.2
    Max_traversable_angle: 55.0
    Num_Colors: 50
    Max_Num_Grids: 10


    Global_map_resolution: 1.0
    Global_map_init_height: 50.0
    Global_map_init_width: 50.0
    Global_map_increment: 20.0


